Feature/background design
samuelcamilocosta/orion-bootcamp-front-boilerplate pull request #10
Opened 2023-10-31 21:25 UTC by Tita-Simoni

2023-10-31 22:31 UTC, alan-rocha-newrizon requested changes

2023-10-31 22:31 UTC, alan-rocha-newrizon commented on src/app/app.component.html
> +  'background-image': true,
Como o posicionamento do background nas páginas é o mesmo, utilizar uma classe só, para manter a aplicação mais concisa e mais limpa.

2023-10-31 22:31 UTC, alan-rocha-newrizon commented on src/app/app.component.ts
> +    this.router.events.subscribe(event => {
tipar a variavel aqui como NavigationEnd, ex `subscribe((event: NavigationEnd) => {})`.

Com isso, você não precisa verificar se ela vai ser uma instância de NavigationEnd, por que vai ser ;)

2023-11-07 09:26 UTC, FLindenmeyer commented on src/app/app.component.ts
> +    this.router.events.subscribe(event => {
acabei removendo essa linha de código pois não vi a necessidade no momento. Estava la sem utilidade.

2023-11-07 09:55 UTC, FLindenmeyer commented
Estava acusando 2 arquivos em conflito e resolvi eles por aqui no github mesmo

2023-11-07 10:32 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Ajuste do background da página inicial e da página de meteorologia](https://trello.com/c/h8WjCFJ6/360-orion-marte-ajuste-do-background-da-p%C3%A1gina-inicial-e-da-p%C3%A1gina-de-meteorologia)

2023-11-08 22:25 UTC, alan-rocha-newrizon requested changes

2023-11-08 22:25 UTC, alan-rocha-newrizon commented on src/app/app.component.ts
> +    // return this.router.url === '/transition';
Essa função não faz nada. Remover.

2023-11-08 22:25 UTC, alan-rocha-newrizon commented on src/app/app.component.ts
> +  isAuthPage(): boolean {
O nome da sua função não condiz com o que ela faz.

Pelo nome, está verificando se a página em questão, é a de login, mas nas condições, verifica se é diferente das rotas de login.

Se a ideia for verificar se são páginas que necessitam estar autenticadas, eu mudaria o nome da função pra alguma coisa do tipo `isPrivatePage`.

Lembrando ainda sobre o que foi mencionado no PR#9, as rotas vão sofrer uma alteração, então você pode apenas verificar se as rotas contém o caminho que deverão conter as rotas privadas.

2023-11-09 09:52 UTC, FLindenmeyer commented on src/app/app.component.ts
> +    // return this.router.url === '/transition';
Função removida.

2023-11-09 22:14 UTC, alan-rocha-newrizon approved these changes

2023-11-09 22:14 UTC, merged