Feature/premium modal component + logout with premium button
samuelcamilocosta/orion-bootcamp-front-boilerplate pull request #20
Opened 2023-11-16 10:51 UTC by FLindenmeyer

2023-11-16 10:55 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Criar modal premium + criar botão premium junto com o de logout.](https://trello.com/c/aXol26VD/547-orion-marte-criar-modal-premium-criar-bot%C3%A3o-premium-junto-com-o-de-logout)

2023-11-16 23:18 UTC, samuelcamilocosta requested changes

2023-11-16 23:18 UTC, samuelcamilocosta commented on src/app/api/v1/base-methods.ts
> +  protected openPremiumModal(): void {
faltou documentar a função

2023-11-16 23:18 UTC, samuelcamilocosta commented on src/app/shared/components/logout-icon/logout.component.scss
> +  .Btn {
CRIME

2023-11-16 23:18 UTC, samuelcamilocosta commented on src/app/shared/components/logout-icon/logout.component.ts
> +  openModal() {
faltou tipar o retorno da função

2023-11-16 23:18 UTC, samuelcamilocosta commented on src/app/shared/components/premium-modal/premium-modal.component.ts
> +  closeDialog() {
faltou tipar a função

2023-11-16 23:18 UTC, samuelcamilocosta commented on src/app/shared/components/premium-modal/premium-modal.component.ts
> +  premiumStyleActive = true; //
remover o //

2023-11-17 22:24 UTC, samuelcamilocosta approved these changes

2023-11-17 22:49 UTC, alan-rocha-newrizon approved these changes

2023-11-17 22:50 UTC, merged