Feature/home page rework + integration of user type
samuelcamilocosta/orion-bootcamp-front-boilerplate pull request #21
Opened 2023-11-17 19:41 UTC by FLindenmeyer

2023-11-17 19:44 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] atualizar pagina home com o carrossel + verificação de perfil na home](https://trello.com/c/Nfr9JbYb/544-orion-marte-atualizar-pagina-home-com-o-carrossel)

2023-11-18 17:04 UTC, alan-rocha-newrizon requested changes

2023-11-18 17:04 UTC, alan-rocha-newrizon commented on src/app/interfaces/login-resp-params-interface.ts
>    user: {
Tipar essa chave user com a sua interface IUser. { user: IUser; }

2023-11-18 17:04 UTC, alan-rocha-newrizon commented on src/app/interfaces/user-interface.ts
> +export interface IUser {
Todos os campos relacionados aos dados do usuário, você coloca nessa interface. Vide os campos que existem na ILoginRespParams.user e não existem aqui.

2023-11-18 17:04 UTC, alan-rocha-newrizon commented on src/app/services/auth/auth.service.ts
> +  isPremium() {
Criar uma função no seu storage service pra verificar se o usuário é premium ou não

2023-11-18 17:04 UTC, alan-rocha-newrizon commented on src/app/services/auth/auth.service.ts
>     *
Criar uma função no storage service para retornar o token do usuário

2023-11-21 22:32 UTC, alan-rocha-newrizon requested changes

2023-11-21 22:32 UTC, alan-rocha-newrizon commented on src/app/api/v1/base-methods.ts
> +      // }
remover esses comentários

2023-11-21 22:32 UTC, alan-rocha-newrizon commented on src/app/services/auth/auth.service.ts
> +  isPremium() {
Faltou a resolução desse ponto

2023-11-21 22:32 UTC, alan-rocha-newrizon commented on src/app/services/auth/auth.service.ts
>     *
faltou a resolução desse ponto

2023-11-22 22:04 UTC, alan-rocha-newrizon approved these changes

2023-11-22 22:05 UTC, merged