Feature/user registration
samuelcamilocosta/orion-bootcamp-front-boilerplate pull request #25
Opened 2023-12-03 23:18 UTC by FLindenmeyer

2023-12-03 23:20 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Cadastro de usuário](https://trello.com/c/hE242ml1/545-orion-marte-cadastro-de-usu%C3%A1rio)

2023-12-05 22:02 UTC, alan-rocha-newrizon requested changes

2023-12-05 22:02 UTC, alan-rocha-newrizon commented on src/app/api/v1/recovery.service.ts
> +    paragraphA: 'E-mail de recuperação enviado com sucesso!',
Esse aqui, você não precisa colocar 2 parágrafos, pode usar uma string HTML usando o formato de template string com crase:
`<p>E-mail de recuperação enviado com sucesso!</p>
<p>Siga as instruções enviadas em seu e-mail.</p>`

2023-12-06 22:46 UTC, alan-rocha-newrizon approved these changes

2023-12-06 23:04 UTC, merged