Feature/login background
samuelcamilocosta/orion-bootcamp-front-boilerplate pull request #5
Opened 2023-10-25 15:10 UTC by Tita-Simoni

2023-10-25 22:27 UTC, alan-rocha-newrizon requested changes

2023-10-25 22:27 UTC, alan-rocha-newrizon commented on src/app/img/Epic-Sky-03 2.png
Mover essa imagem para a pasta `src/assets/img` e atualizar no arquivo app.component.scss

2023-10-26 21:04 UTC, Tita-Simoni commented on src/app/img/Epic-Sky-03 2.png
Concluído

2023-10-26 22:04 UTC, alan-rocha-newrizon approved these changes

2023-10-26 22:05 UTC, merged