Feature/Recovery password page /Enhancements
samuelcamilocosta/orion-bootcamp-front-boilerplate pull request #6
Opened 2023-10-26 17:29 UTC by FLindenmeyer

This pull request includes a series of commits aimed at enhancing and adding new features to our application. The changes can be summarized as follows:

- Added API integration on login-page
- Implemented a real-time notification feature.
- Update SCSS files for improved design

2023-10-26 17:33 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Criação do componente da página de recuperação de senha e rota + integração com a API na página de login](https://trello.com/c/ysxBUIkj/316-orion-marte-cria%C3%A7%C3%A3o-do-componente-da-p%C3%A1gina-de-recupera%C3%A7%C3%A3o-de-senha-e-rota-integra%C3%A7%C3%A3o-com-a-api-na-p%C3%A1gina-de-login)

2023-10-26 22:17 UTC, alan-rocha-newrizon requested changes

2023-10-26 22:17 UTC, alan-rocha-newrizon commented on src/app/api/v1/login.service.ts
> +      .subscribe((res) => console.log(res));
você usando esse .subscribe aqui, o componente que chamar a sua função não vai receber dado algum, com isso, você não consegue capturar lá, nem sucesso, nem erro. sugiro, no lugar de usar o subscribe, utilizar `toPromise()` no retorno. Com isso, lá no seu componente de login, você consegue usar um `await` para aguardar a resposta e capturar os dados.

2023-10-26 22:17 UTC, alan-rocha-newrizon commented on src/app/login-page/login-page.component.ts
> +      this.loginService.sendData(data);
aqui não há nenhum tratamento de erro para o caso de erro na resposta.
Outro ponto, você não consegue pegar nenhum dado retornado pelo serviço, por que foi utilizado o subscribe lá no serviço. Caso opte por utiliza o toPromise como sugerido, aqui você deverá usar um await para aguardar os dados de retorno.

Indico também utilizar um try/catch para tratar a exceção de usuário e senha inválidos.

E por último, o token não está sendo armazenado em lugar algum, com isso, o usuário, mesmo fazendo o login, não vai estar realmente logado no sistema. o ideial seria armazenar isso ou em ou localStorage ou sessionStorage, dependendo da escolha do usuário de acordo com a opção `Lembrar de mim` para isso, criar um serviço especifico para tratar essa finalidade

2023-10-27 22:27 UTC, alan-rocha-newrizon requested changes

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/api/v1/login.service.ts
> +  async sendData(data: ILoginParams): Promise<ILoginRespParams> {
falta tsdoc do método

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/components/error-dialog/error-dialog.component.ts
> +  closeDialog(): void {
adicionar docmentação da função

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/login-page/login-page.component.ts
> +  async onSubmit() {
Adicionar documentação da função.

Essa sua função também não trata uma exceção. No seu login service, você tratou a exceção pro caso de erro 400, qualquer outro problema que você venha a ter no código,, vai te dar problema

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/login-page/login-page.component.ts
> +  ngOnInit(): void {
adicionar documentação da função

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/services/auth/auth.service.ts
> +  setLocalItem(key: string, value: ILoginRespParams): boolean {
Adicionar documentação da função

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/services/auth/auth.service.ts
> +  setSessionItem(key: string, value: ILoginRespParams): boolean {
Adicionar documentação da função

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/services/auth/auth.service.ts
> +  getLocalItem(key: string): string | null {
Adicionar documentação da função

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/services/auth/auth.service.ts
> +  getSessionItem(key: string): string | null {
Adicionar documentação da função

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/services/auth/auth.service.ts
> +  removeItem(key: string) {
Adicionar documentação da função

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/services/auth/auth.service.ts
> +  isAuthenticated(): boolean {
Adicionar documentação da função

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/api/v1/login.service.ts
> +  openDialog(): void {
Adicionar documentação da função

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/login-page/login-page.component.ts
> +    if (this.formGroup.get('checkbox')?.value) {
não faça esse tratamento aqui, crie no seu serviço uma função que receba o token e se é pra lembrar ou não, e trate lá dentro. código do seu componente fica mais limpo.

2023-10-27 22:27 UTC, alan-rocha-newrizon commented on src/app/login-page/login-page.component.ts
> +    if (this.auth.isAuthenticated()) {
aqui você não precisa verificar se está autenticado ou não, por que tem que estar, acabou de fazer o login, e teve sucesso.

2023-10-30 21:59 UTC, alan-rocha-newrizon approved these changes

2023-10-30 21:59 UTC, merged