Feature/route guard for home page
samuelcamilocosta/orion-bootcamp-front-boilerplate pull request #7
Opened 2023-10-29 20:28 UTC by FLindenmeyer

2023-10-29 20:30 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Proteção das rotas privadas da aplicação](https://trello.com/c/Dyz3LJQV/389-orion-marte-prote%C3%A7%C3%A3o-das-rotas-privadas-da-aplica%C3%A7%C3%A3o)

2023-10-29 20:35 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Proteção das rotas privadas da aplicação](https://trello.com/c/Dyz3LJQV/389-orion-marte-prote%C3%A7%C3%A3o-das-rotas-privadas-da-aplica%C3%A7%C3%A3o)

2023-10-31 21:36 UTC, alan-rocha-newrizon requested changes
O funcionamento está ok, a implementação não está ideal.

Utilize a implementação criando uma classe injetavel ( utilize o decorator @Injectable ).

Essa sua classe deve implementar o CanActivate, e no construtor, você injeta as dependencias do router e AuthService.

segue um tutorial explicativo no link https://www.scaler.com/topics/auth-guard-in-angular/

2023-11-06 22:33 UTC, alan-rocha-newrizon approved these changes

2023-11-06 22:34 UTC, merged