Feature/home page
samuelcamilocosta/orion-bootcamp-front-boilerplate pull request #8
Opened 2023-10-31 20:32 UTC by FLindenmeyer

2023-10-31 20:33 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] Criação do componente da página inicial, rota e cabeçalho (título e botão de sair)](https://trello.com/c/T3RzDUuq/358-orion-marte-cria%C3%A7%C3%A3o-do-componente-da-p%C3%A1gina-inicial-rota-e-cabe%C3%A7alho-t%C3%ADtulo-e-bot%C3%A3o-de-sair)

2023-10-31 21:54 UTC, alan-rocha-newrizon requested changes

2023-10-31 21:54 UTC, alan-rocha-newrizon commented on src/app/pages/home-page/home-page.component.html
> +      <app-card
Você tem a interface ICard, utilize ela como parametro de entrada do componente, tendo apenas um parametro do tipo ICard.

2023-10-31 21:54 UTC, alan-rocha-newrizon commented on src/app/shared/components/home-card/home-card.component.html
> +    alt="red rocks from mars"
Texto alternativo é boa prática de acessibilidade, bom utilizar, mas não pode ser fixo para todos os elementos.

2023-10-31 21:54 UTC, alan-rocha-newrizon commented on src/app/shared/components/home-card/home-card.component.ts
> +  @Input() cardImage = '';
Como mencionado no arquivo da página home, como você possuí a interface ICard, que define o tipo dos parametros para o card, utilize apenas um parametro @Input() que receberá um objeto do tipo ICard

2023-11-06 22:39 UTC, alan-rocha-newrizon approved these changes

2023-11-06 23:00 UTC, merged