Criação do componente e página de metereologia
samuelcamilocosta/orion-bootcamp-front-boilerplate pull request #9
Opened 2023-10-31 20:39 UTC by Tita-Simoni

2023-10-31 22:17 UTC, alan-rocha-newrizon requested changes
faltou a implementação da rota para a página de meteorologia

2023-11-07 09:55 UTC, FLindenmeyer commented
Estava acusando 2 arquivos em conflito e resolvi eles por aqui no github mesmo

2023-11-07 10:33 UTC, FLindenmeyer commented
![](https://github.trello.services/images/mini-trello-icon.png) [[ORION MARTE] - Criar o componente da pagina de metereologia, a rota e cabeçalho (título e botão de sair)](https://trello.com/c/JOqowBMa/363-orion-marte-criar-o-componente-da-pagina-de-metereologia-a-rota-e-cabe%C3%A7alho-t%C3%ADtulo-e-bot%C3%A3o-de-sair)

2023-11-08 22:08 UTC, alan-rocha-newrizon requested changes

2023-11-08 22:08 UTC, alan-rocha-newrizon commented on src/app/app-routing.module.ts
> +   {
Criar um rota raiz, e colocar a rota /home e /meteorology como filhas da mesma.
Com isso, não haverá a necessidade de se aplicar o route guard a todas as rotas da aplicação, bem como, não haverá a necessidade de ficar se repetindo o caminho inicial da rota, como no estado desse arquivo é /home.

2023-11-09 22:06 UTC, alan-rocha-newrizon approved these changes

2023-11-09 22:06 UTC, merged